language: python
python:
- '3.4'
sudo: true
before_install:
- pip install requests
- echo 'America/Los_Angeles' | sudo tee /etc/timezone
- sudo dpkg-reconfigure --frontend noninteractive tzdata
install:
- if [ "${TRAVIS_SECURE_ENV_VARS}" = "true" ] ; then ./shared/dev-tasks/travis-install-ml.sh
  release ; else (exit 0) ; fi
- if [ "${TRAVIS_SECURE_ENV_VARS}" = "true" ] ; then ./shared/dev-tasks/setup-marklogic.sh
  ; else (exit 0) ; fi
script:
- python setup.py test
env:
  global:
  - secure: PnQR4S2RarIhtnZaN1jOd3RyCH3L1PhQ+AAxhmmlO9xqJ8NJ4PCzOIC86e/BK5RiobFscxU0vQIb7wNIIbw0sKKykYg3lWRlusrW7IJ2fEuLj/sm/ixgnh2S8KTz+DzjbLPbN8N5W1spu4cdYNIBFb5hOMHFU+xZ3Vi/SKlQDyvqjUicY/JIKKjYn572Hg5UgEIwUt2QCzWZ/2brRR8jqLC5EiUnT6UbfNIfXIBKQM8z80C/neWGSMDZVFHEnRJHxI+RvPdAqEkSFtvT/zAb/C1n5r//AShBECt9LA09CRC5MZicgAJOKJ1EvlCus92xxeu7JjC96fZ2yBI2ZmkaZoN4o5IBUkNOG8HB5gX6vpAR2PI/GqWj3ubSmrcoWBm7dudju/PRvCAt0wUwt+xAxfIlHuFQCfjaEwr5mOMVLlDxCIrEgVhZxdTqHGPOHAleZqIvycjT5QOflNdFpmWRx04Y121w+gaSfAW6rUHkTt1+UeF+GFFK5gh78hjFy43/V/7M+U6M/DHQExy63bs0r07biIMfEYbKLocEoJcPj1RwZpvQCo28jrLTdwCnbLsdCDsWbK0wojvmKhxXl5j8J8uRSyd5egwu9h3qYZdmJTzk8904cfPYDhPWDc+rauro0gRbFCx0JRtkHiDUYEfHbUWNvW/bXupUp2LHZ2+3OYU=
  - secure: QYaSKzNeEexu8YiLA1il9Nn5+DCvFRosIoLiZRtOobMgywHD5sL0xuj04dxP20yvapkdXOLB8MMF5Z+EZLqM4QvMx3bO+EoXNcVd/SQDa1eXIEihdAy9+o8jgIHgF6DTzApvBIbDDy6d4WJDud3lQ/7Mq6ysK4K0YXUS5458TuCNxx7v7gmJp1cZfvaBxMxEua5U/IgzY4/K4Uo14adC15aJ1tUM4bxj3ByYk+LUFVkkk/kNrgTFZoipxAyq1qKTjntQ3GP7K/9cQ6EqVWgkV4DA54CgZLypHdwwIm6ODE3uktTYmuZ425Uvk8vjsKkpQTNGvBu++NK4Y1JehFDqn9HFWrZ9jAIciDaIL0dHvas634jeL65xanB6IzliUFmnWIP3eIS84UedIiAkz6TIpO6f7HOf4ja1IG19d4WtwmD2p+RFPzAlIOstKg3bMauyG8e952tPH5IAqIGA68avtlDeNOMnCP9jN6/DyozcTYaMguq6prhHUIb7Xzo5w6oGS/rq8ctkcL/BkAcGd8KgYYIqXJCckwZdE0HOeUJRUjUguXLvpStFXRycoa2bwg61tJUsLwitO87Gs2iY9Op96tkpfFESZpfqFN+Yc+hxhikRi8mXwnzn5RLp6xCVuYVAF+ioEYP+Ygsd6/3rLStgWFsmfCJ46WkgYRtnOQ+0+Zs=
